version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    expose:
      - "3306"
    #ports:
    #  - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_service
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql_data:/var/lib/mysql

  board-mysql:
    image: mysql:latest
    container_name: board-mysql
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: board_service
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./board_mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    #ports:
    #  - "6379:6379"  

  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    expose:
      - "8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/user_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - JWT_SECRET_KEY=${REAL_JWT_SECRET}
      - REDIS_HOST=redis
    depends_on:
      - mysql
  board-service:
    image: board-service:latest
    container_name: board-service
    build:
      context: ./board-service
      dockerfile: Dockerfile
    expose:
      - "8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://board-mysql:3306/board_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - JWT_SECRET_KEY=${REAL_JWT_SECRET}
    depends_on:
      - board-mysql

  lucky-gateway:
    image: lucky-gateway:latest
    container_name: lucky-gateway
    build:
      context: ./lucky-gateway
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8081
      - BOARD_SERVICE_URL=http://board-service:8082
      - JWT_SECRET_KEY=${REAL_JWT_SECRET}
    depends_on:
      - user-service
      - board-service

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - lucky-gateway