apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-mysql
spec:
  selector:
    matchLabels:
      app: user-service-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-service-mysql
    spec:
      containers:
      - image: mysql:latest
        name: user-service-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "user_service"
        ports:
        - containerPort: 3306
          name: mysql
        args:
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_unicode_ci"
        volumeMounts:
        - name: user-service-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: user-service-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: user-service-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: user-service-mysql
  type: ClusterIP