server:
  port: 8000

spring:
  application:
    name: lucky-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        - id: board-service
          uri: ${BOARD_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/board-service/**
          filters:
            - StripPrefix=1
            - AuthorizationHeaderFilter